# Generated by Django 5.0.6 on 2025-06-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('subcategory', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.TextField(default='', max_length=1000)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(upload_to='images/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='contant',
            name='created_at',
        ),
    ]
