# Generated by Django 5.2.5 on 2025-08-22 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_contact_orders_orderupdate_delete_contant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ecommerceapp.orders')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KhaltiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_id', models.CharField(max_length=100)),
                ('purchase_order_name', models.CharField(max_length=200)),
                ('return_url', models.URLField()),
                ('website_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='EsewaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.CharField(max_length=50)),
                ('product_code', models.CharField(max_length=50)),
                ('transaction_uuid', models.CharField(max_length=100, unique=True)),
                ('signature', models.TextField()),
                ('success_url', models.URLField()),
                ('failure_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.paymenttransaction')),
            ],
        ),
    ]
