# Generated by Django 5.2.5 on 2025-10-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_alter_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
